import type { Metadata } from 'next';
import '@/styles/globals.css';
import { actay, chakrapetch, jersey10 } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${actay.variable} ${chakrapetch.variable} ${jersey10.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
